#!/usr/bin/env python3
"""Outline the masthead wordmark "FreeWRL" into SVG paths.

The lettering in the FreeWRL logo is a heavy, rounded sans: white letters,
the two "e"s in yellow, with a dark edge. No font file for it is recorded,
so the site uses Nunito Black (SIL OFL 1.1, from npm @fontsource/nunito)
as the closest free match, converted to outlines. The site does not load
Nunito; only these path outlines ship, in src/components/wordmark-paths.ts.

Run: python3 scripts/make_wordmark.py <path to nunito-latin-900-normal.woff2>
(needs fontTools + brotli). Get the font with: npm pack @fontsource/nunito@5
"""
import sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

ROOT = Path(__file__).resolve().parent.parent
font = TTFont(sys.argv[1])
cmap, glyphs, hmtx = font.getBestCmap(), font.getGlyphSet(), font["hmtx"]
upm = font["head"].unitsPerEm
asc = font["OS/2"].sCapHeight  # cap height: top of the letters
TRACK = -0.01 * upm            # a little tighter than the font, like the logo
PAD = 60                       # room for the outline stroke

x, parts = PAD, []
for ch in "FreeWRL":
    g = cmap[ord(ch)]
    pen = SVGPathPen(glyphs)
    # font units are y-up; flip into SVG space with the cap height at PAD
    glyphs[g].draw(TransformPen(pen, (1, 0, 0, -1, x, asc + PAD)))
    parts.append((ch, pen.getCommands()))
    x += hmtx[g][0] + TRACK
width = round(x - TRACK + PAD)
desc = 0  # "FreeWRL" has no descenders
height = round(asc + desc + 2 * PAD)

out = ["// Generated by scripts/make_wordmark.py from Nunito Black (SIL OFL 1.1). Do not edit.",
       f"export const WORDMARK_VIEWBOX = \"0 0 {width} {height}\"",
       "export const WORDMARK_GLYPHS: { ch: string; d: string; accent: boolean }[] = ["]
for ch, d in parts:
    out.append(f"  {{ ch: {ch!r}, accent: {str(ch == 'e').lower()}, d: \"{d}\" }},".replace("'", '"'))
out.append("]")
(ROOT / "src/components/wordmark-paths.ts").write_text("\n".join(out) + "\n")
print("viewBox", width, height)
