// Copy the pinned X_ITE build from node_modules into public/x_ite/<version>/.
// X_ITE resolves its components, fonts and libraries relative to its own
// module URL (import.meta.url), so it must be served as real files, not
// bundled by Vite. Only minified files are copied; the source maps, the
// unminified duplicates and the 6.8 MB x_ite.zip are left out.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const pkg = JSON.parse(readFileSync(join(root, "node_modules/x_ite/package.json"), "utf8"))
const want = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).dependencies.x_ite
if (pkg.version !== want) {
  console.error(`x_ite in node_modules is ${pkg.version}, package.json pins ${want}. Run npm ci.`)
  process.exit(1)
}
const src = join(root, "node_modules/x_ite/dist")
const outBase = join(root, "public/x_ite")
const out = join(outBase, pkg.version)
if (existsSync(outBase)) rmSync(outBase, { recursive: true })
mkdirSync(out, { recursive: true })

cpSync(join(src, "x_ite.min.mjs"), join(out, "x_ite.min.mjs"))
cpSync(join(src, "x_ite.css"), join(out, "x_ite.css")) // loaded by X_ITE into its shadow DOM
cpSync(join(src, "LICENSE.md"), join(out, "LICENSE.md"))
cpSync(join(src, "assets"), join(out, "assets"), {
  recursive: true,
  filter: (p) => !(p.includes("/components/") && p.endsWith(".js") && !p.endsWith(".min.js")),
})
writeFileSync(join(root, "src/generated-xite.ts"),
  `// generated by scripts/sync-xite.mjs — do not edit\nexport const XITE_VERSION = ${JSON.stringify(pkg.version)}\n` +
  `// Self-hosted by default. To use the CDN instead, set VITE_XITE_BASE=https://cdn.jsdelivr.net/npm/x_ite@${pkg.version}/dist/\n` +
  `export const XITE_BASE: string = import.meta.env.VITE_XITE_BASE ?? \`/x_ite/${pkg.version}/\`\n`)
console.log(`x_ite ${pkg.version} -> public/x_ite/${pkg.version}/`)
